name: heavens-vault-dictionary
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - autopep8
  - coverage
  - flake8
  - ipdb
  - ipython
  - overrides
  - pytest
  - pytest-cov
  - rope
